# config/config.yaml
app:
  name: "myapp"
  environment: "development"
  port: 8080

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "pwge24"
  name: "sikad_Absensi"
  sslmode: "disable"
